In [2]:
import torch_geometric

/root/miniforge3/envs/uma/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [85]:
# Length unit (Angstrom in pyscf)
ANG2BOHR = 1.8897261258369282     # Angstrom to Bohr conversion
BOHR2ANG = 0.5291772105638411     # Bohr to Angstrom conversion

# Energy unit (Eh in pyscf)
HA2eV    = 27.211396641308        # Hartree to eV conversion
HA2meV   = HA2eV * 1000           # Hartree to meV conversion
eV2HA    = 0.03674932247495664    # eV to Hartree
meV2HA   = eV2HA / 1000           # meV to Hartree

KCALPM2eV  = 0.04336410390059322   # kcal/mol to eV conversion
KCALPM2meV = KCALPM2eV * 1000      # kcal/mol to meV conversion
HA2KCALPM  = 627.5094738898777     # Hartree to kcal/mol
KCALPM2HA  = 0.001593601438080425  # kcal/mol to Hartree

In [3]:
md17 = torch_geometric.datasets.MD17

In [ ]:
root = "/root/25DFT/data/original_md17"
aspirin = md17(root=root, name="aspirin")

Processing...
Done!
/root/miniforge3/envs/uma/lib/python3.12/site-packages/torch_geometric/datasets/md17.py:364: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.data, sel

In [ ]:
root = "/root/25DFT/data/original_md17"
Ethanol = md17(root=root, name="ethanol")


/root/miniforge3/envs/uma/lib/python3.12/site-packages/torch_geometric/data/dataset.py:208: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  if osp.exists(f) and torch.load(f) 

KeyboardInterrupt: 

In [12]:
Salicylic_acid = md17(root=root, name="salicylic acid")

Processing...
Done!


In [33]:
Napthalene = md17(root=root, name="naphtalene")

Processing...
Done!
/root/miniforge3/envs/uma/lib/python3.12/site-packages/torch_geometric/datasets/md17.py:364: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.data, sel

In [13]:
import numpy as np

In [24]:
data = np.load("/root/25DFT/data/original_md17/aspirin/raw/md17_aspirin.npz")

In [41]:
list(data.keys())

['E', 'name', 'F', 'theory', 'R', 'z', 'type', 'md5']

In [29]:
data['z']

array([6, 6, 6, 6, 6, 6, 6, 8, 8, 8, 6, 6, 8, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=uint8)

In [ ]:
data['R'].shape

(211762, 21, 3)

In [35]:
Napthalene[0].z

tensor([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
Salicylic_acid[0].z

tensor([6, 6, 6, 8, 6, 6, 6, 6, 8, 8, 1, 1, 1, 1, 1, 1])

In [37]:
aspirin[0].z

tensor([6, 6, 6, 6, 6, 6, 6, 8, 8, 8, 6, 6, 8, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
len(data)

8

In [39]:
data["theory"]

array('aims: PBE+TS, light tier 1', dtype='<U26')

In [42]:
len(data["E"])

211762

In [44]:
data["R"].shape

(211762, 21, 3)

In [46]:
data["E"][0]

array([-406757.59126402])

In [48]:
data["F"][0].shape

(21, 3)

In [49]:
import pyscf

In [59]:
Napthalene[0]

Data(pos=[18, 3], z=[18], energy=[1], force=[18, 3])

In [64]:
# cur_data = Napthalene[0]
cur_data = Salicylic_acid[0]
cur_pos = cur_data.pos
cur_z = cur_data.z
mol = pyscf.gto.Mole()
mol_conf = [[cur_z[i], cur_pos[i]] for i in range(len(cur_z))]


In [ ]:
mol.build(verbose=0, atom=mol_conf, basis="def2svp", unit="ang")
mf = pyscf.scf.RKS(mol)
mf = mf.density_fit(only_dfj=True, auxbasis="weigend")  # def2/J 계열
# mf.xc = "pbe+TC"
mf.xc = "pbe"
mf.grids.level = 4
# mf.conv_tol = 1e-9
mf.get_ovlp().shape

(170, 170)

In [122]:
# mf.xc = "pbe+TC"

In [ ]:
energy = mf.kernel()
print(mf.cycles)
print(energy)
print(energy * HA2KCALPM)
print(cur_data.energy)

In [120]:
print(mf.cycles)
print(energy)
print(energy * HA2KCALPM)
print(cur_data.energy)

14
-495.0967048021828
-310677.87275502976
tensor([-311033.5938])
